## set directories ##
# in #
indir_lso: "data_provided/" 
indat_lso: "vacs_lso_parenting.csv"

# out #
outdir_lso: "data_derived/parenting_model"

## tables ##
outdat_summary: "table_summary_stats.docx"
outdat_correlation: "table_correlation.doc"
outdat_log: "table_logistic_regression.docx"
outdat_marg: "table_marginal_effects.docx"
